[SBL-125] 헤더 반응형 css 작업 및 저장 불가 사유 안내 모달 추가
SUIN-BUNDANG-LINE/Frontend pull request #51
Opened 2024-09-19 15:50 UTC by yooshnn

## 📢 설명
![image](https://github.com/user-attachments/assets/12f744dc-546d-43c0-88fd-012e37f3b758)
반응형 헤더 (헤더는 320px까지 지원, 제작 UI는 420px까지 지원)

![image](https://github.com/user-attachments/assets/1ec6fc47-20ab-44ca-8aa3-754a48bd5773)
클라이언트 레벨에서 감지한 에러

저장도 일단은 되지만 이 PR에서는 다루지 않습니다

## ✅ 체크 리스트
- [ ] 섹션이나 질문의 제목을 출력하는 각종 상황에서 빈 문자열에 대한 대응 (공개 준비, 에러 목록 등)
- [ ] `validate` 함수에서 놓친 문제 혹은 잘못 구현된 로직 없는지...
- [ ] 그 밖의 workbench UI에 전체적으로 문제 없는지 확인

2024-09-19 17:56 UTC, JeongHunHui requested changes
고생 많으셨습니다! 아래 문제들 수정 부탁드려요.....

1. finishedAt 형식이 백엔드와 맞지 않습니다.
    
    프론트엔드 형식: `Mon Sep 30 2024 00:00:00 GMT+0900`
    
    백엔드 형식: `2024-09-23T15:00:00.000Z`
    
2. 리워드 추가 모달에서 띄어쓰기가 안됩니다. 아마 입력할 때 문자열 시작과 끝에 공백을 제거해서 그런 것 같은데 저장할 때 공백을 제거하면 어떨까 싶습니다.
    
    ![image](https://github.com/user-attachments/assets/e945c61e-1496-4dd7-814f-366db389a04d)
    
3. `리워드`, `마감 일정`, `목표 참여자 수`를 입력한 상태에서 리워드 지급 방식을 변경하면, 기존 정보들이 유지되어 에러가 발생합니다. 지급 방식 변경 시 상태를 초기화 하거나, 각 지급 방식에 필요한 정보만 넣어주도록 해야할 것 같습니다.
    
    ![image](https://github.com/user-attachments/assets/ba8d9d47-2963-41a6-95eb-eaaf543ba525)
    
    ![image](https://github.com/user-attachments/assets/acdf9a7e-1928-4e4b-82ef-bb3417f95582)
    
4. 단일 선택 & 필수 질문 생성 → 선택지 라우팅 설정 → 선택지 추가 → 선택지 내용 변경 시 `choices`는 정상적으로 업데이트 되는데, `sectionRouteConfigs`의 `content`는 업데이트가 안됩니다. (아래 스샷에서는 `choices`에선 `"1"` 선택지가 있지만, `sectionRouteConfigs`에는 `""`이 들어가있음)
    
    ![image](https://github.com/user-attachments/assets/d87e8676-e282-492e-bb55-843b0232b73f)
    
5. 선택지 라우팅 설정 후 목적지 섹션 제거 시 아래같이 정상적으로 다음 섹션으로 자동 설정되는 듯 보이나, 저장이 불가하다고 나타납니다.
    
    ![image](https://github.com/user-attachments/assets/f01afe10-23c0-4945-97b9-290969ccb8cc)
    
    ![image](https://github.com/user-attachments/assets/eb1519b3-0497-44f4-9fc6-e9cc11a48c81)

2024-09-19 18:17 UTC, JeongHunHui commented
추가적으로, 아래 부분들은 validate 함수에서 누락된 것 같습니다.
1. reward count > 0
2. 즉시 추첨 시 목표 참여자 수 >= 리워드 count 총합

2024-09-20 03:27 UTC, yooshnn commented
1~4번 해결 완료

2024-09-23 11:07 UTC, JeongHunHui approved these changes
고생 많으셨습니다.

2024-09-23 11:08 UTC, merged