[SBL-124] 설문 통계 탭 구현
SUIN-BUNDANG-LINE/Frontend pull request #53
Opened 2024-09-23 20:19 UTC by JeongHunHui

## 📢 설명
![image](https://github.com/user-attachments/assets/e99baea4-c286-48b8-9403-9d1dd1b5d1c5)
- 설문 통계 탭을 구현했습니다.

## ✅ 체크 리스트

- [ ]  마이페이지에서 진행 중인 설문을 클릭해서 설문 관리페이지 진입
- [ ]  정상적으로 응답들이 보이는지 확인
- [ ]  필터 추가 후 질문을 고르지 않거나, 필터링할 응답을 고르지 않은 상태에서 검색 버튼을 클릭한 경우 아래와 같이 예외 처리를 하는지 확인
    
    ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/eb5a2038-3329-4b33-8875-d48fc507eb51/1f9be1ab-9370-4f8d-a2ab-9289fefa46ef/image.png)
    
- [ ]  필터를 20개 보다 많이 추가하려고 할 때 아래와 같이 예외 처리를 하는지 확인
    
    ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/eb5a2038-3329-4b33-8875-d48fc507eb51/fd1c641f-cd81-4f03-9ecb-c97a1a64a9fe/image.png)
    
- [ ]  필터에 따라 응답이 잘 필터링 되는지 확인
- [ ]  반응형 ui가 잘 구성되었는지 화면 크기 변경하면서 확인
    
    ![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/eb5a2038-3329-4b33-8875-d48fc507eb51/0e0819cc-97c2-4c15-b419-102e13d463ac/image.png)
    
- [ ]  코드 리뷰

2024-09-24 05:18 UTC, yooshnn commented
필터에서 질문을 선택하면 다음과 같이 contents가 undefined로 나오고 에러가 발생해 테스트가 불가합니다.

```
{type: 'SINGLE_CHOICE', title: '직업을 골라주세요.', id: '3fa1b7fd-58c4-45d6-b38c-3c568fd9787c', contents: undefined}
```

2024-09-24 05:21 UTC, yooshnn requested changes
필터에서 질문을 선택하면 다음과 같이 contents가 undefined로 나오고 에러가 발생해 테스트가 불가합니다.

```
{type: 'SINGLE_CHOICE', title: '직업을 골라주세요.', id: '3fa1b7fd-58c4-45d6-b38c-3c568fd9787c', contents: undefined}
```

1. 단일 선택, 복수 선택, 텍스트 입력 아이콘은 다른 페이지와 통일해주세요.
2. 마이 페이지에서 `응답 받는 중`인 설문이 `마감된 설문`으로 표기됩니다.
3. 관리 페이지에서 응답자 수가 표기되지 않습니다.
4. 열기 / 닫기 버튼은 삼각형 대신 텍스트로 해주세요. (의도를 파악하기 어렵습니다.)

![image](https://github.com/user-attachments/assets/1adb334b-4d2e-4cbb-9acb-c137bd09eb3c)

2024-09-24 16:23 UTC, JeongHunHui commented
> 필터에서 질문을 선택하면 다음과 같이 contents가 undefined로 나오고 에러가 발생해 테스트가 불가합니다.

> 3. 관리 페이지에서 응답자 수가 표기되지 않습니다.

위 두가지 문제는 관련 백엔드 작업이 아직 Merge되지 않았어서 해당 문제가 발생한 것으로 보입니다. 이제는 Merge되었으니 다시 리뷰 부탁드립니다!

> 2. 마이 페이지에서 응답 받는 중인 설문이 마감된 설문으로 표기됩니다.

이 문제는, 현재 백엔드에서 마감일이 되어도 아직 마감을 시키는 스케줄러가 없어서 상태 업데이트가 안되었기 때문입니다. 추후에 백엔드 쪽에서 설문 종료 스케줄러를 구현하겠습니다. 테스트용으로 사용 중인 음식 선호도 조사 설문은 마감일을 연장해두었으니 다시 확인 부탁드립니다.

> 1. 단일 선택, 복수 선택, 텍스트 입력 아이콘은 다른 페이지와 통일해주세요.

> 4. 열기 / 닫기 버튼은 삼각형 대신 텍스트로 해주세요. (의도를 파악하기 어렵습니다.)

반영했습니다!

2024-09-26 04:22 UTC, yooshnn approved these changes
잘 반영된거 확인했어요 css만 조금 수정합니다

2024-09-26 04:23 UTC, merged